spring:
  application:
    name: ${APP_NAME:TELEGRAM_BOT}
  liquibase:
    enabled: false
    change-log: db/changelog/master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8484

springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    try-it-out-enabled: true
  api-docs:
    path: /api/docs

#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui
#    groups-order: asc
#    operations-sorter: alpha
#    try-it-out-enabled: true
#    tags-sorter: alpha
#    display-request-duration: true
#    doc-expansion: "none"
#  api-docs:
#    path: /api/docs
